# Generated by Django 2.2.16 on 2021-03-17 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api_rest", "0017_auto_20210317_1307"),
    ]

    operations = [
        migrations.RunSQL(
            """CREATE OR REPLACE FUNCTION after_update_epidemiology_record()
  RETURNS trigger AS
$$
begin
	IF new.resultado <> 'PENDIENTE' THEN
       UPDATE api_rest_datahigienemodel SET processed = true  where codigo = new.no_muestra;
    END IF;	
  return new;
END;

$$
LANGUAGE 'plpgsql';""",
            "DROP FUNCTION IF EXISTS after_update_epidemiology_record();",
        ),
        migrations.RunSQL(
            """
 CREATE TRIGGER resultado_changes
  BEFORE UPDATE
  ON api_rest_dataepidemiologiamodel
  FOR EACH ROW
  EXECUTE PROCEDURE after_update_epidemiology_record();
  """,
            "DROP TRIGGER IF EXISTS resultado_changes ON api_rest_dataepidemiologiamodel;",
        ),
    ]
