# Generated by Django 2.2.16 on 2021-04-23 21:06

from django.db import migrations
from django.contrib.postgres.operations import (
    UnaccentExtension,
    TrigramExtension,
)


class Migration(migrations.Migration):

    dependencies = [
        ("nucleo", "0001_create_trigger"),
    ]

    operations = [
        UnaccentExtension(),
        TrigramExtension(),
    ]
