stages:
  - lint
  - test

variables:
  POSTGRES_USER: 'covid19grm'
  POSTGRES_PASSWORD: 'covid19grm'
  POSTGRES_DB: 'test_cti'
  POSTGRES_HOST_AUTH_METHOD: trust
  
  
  # This will instruct Docker not to start over TLS.
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2
  

linting:
  stage: lint
  image: python
  tags:
    - docker
  before_script:
    - pip --proxy=http://proxy22.udg.co.cu:3128 install -q flake8
  script:
    - flake8

tests:
  stage: test
  image: python
  image: docker/compose
  tags:
    - docker
  before_script:
    - docker-compose -f docker-compose-test.yml down --remove-orphans || true
    - docker-compose -f docker-compose-test.yml build
    - docker-compose -f docker-compose-test.yml up -d
  script:
    - echo "Testing api"    
    - docker-compose -f docker-compose-test.yml run --rm api python manage.py test --settings=MERCES.settings.docker --keepdb
  after_script:
     - docker-compose -f docker-compose-test.yml down --remove-orphans || true

