# Generated by Django 2.2.16 on 2021-03-12 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataEpidemiologiaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('covid_plus', models.CharField(blank=True, max_length=255, unique=True, verbose_name='Covid+')),
                ('no_pcr_realizado', models.CharField(blank=True, max_length=255, unique=True, verbose_name='No PCR Realizado')),
                ('no_muestra', models.CharField(blank=True, max_length=255, unique=True, verbose_name='No Muestra')),
                ('laboratorio', models.CharField(max_length=255, verbose_name='Laboratorio')),
                ('nombre_apellido', models.CharField(max_length=255, verbose_name='Nombres y Apellidos')),
                ('ci_pasaporte', models.CharField(max_length=255, verbose_name='CI o Pasaporte')),
                ('edad', models.IntegerField(verbose_name='Edad')),
                ('sexo', models.CharField(max_length=1, verbose_name='Sexo')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección')),
                ('municipio', models.CharField(blank=True, max_length=255, verbose_name='Municipio')),
                ('aislamiento', models.CharField(blank=True, max_length=255, verbose_name='Aislamiento')),
                ('fis', models.CharField(max_length=255, verbose_name='FIS')),
                ('muestra', models.CharField(max_length=255, verbose_name='Muestra')),
                ('ftm', models.DateField(verbose_name='FTM')),
                ('fecha_envio', models.DateField(verbose_name='Fecha de envío')),
                ('resultado', models.CharField(default='Pendiente', max_length=255, verbose_name='Resultados')),
                ('fecha_resultado', models.DateField(blank=True, null=True, verbose_name='Fecha del resultado')),
                ('pcr_contactos_viajeros', models.DateField(verbose_name='PCR de los Contactos y Viajeros')),
                ('condicion', models.CharField(max_length=255, verbose_name='Condición')),
                ('pais', models.CharField(max_length=255, verbose_name='País')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
            ],
            options={
                'ordering': ['no_muestra'],
            },
        ),
        migrations.CreateModel(
            name='DataHigieneModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laboratorio', models.CharField(max_length=255, verbose_name='Laboratorio')),
                ('codigo', models.CharField(blank=True, max_length=255, unique=True, verbose_name='Código')),
                ('ci_pasaporte', models.CharField(max_length=255, verbose_name='CI o Pasaporte')),
                ('fecha_toma_muestra', models.DateField(verbose_name='Fecha de Toma Muestra')),
                ('edad', models.IntegerField(verbose_name='Edad')),
                ('sexo', models.CharField(max_length=1, verbose_name='Sexo')),
                ('nombre_apellidos', models.CharField(max_length=255, verbose_name='Nombres y Apellidos')),
                ('condicion', models.CharField(max_length=255, verbose_name='Condición')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección')),
                ('municipio', models.CharField(blank=True, max_length=255, verbose_name='Municipio')),
                ('provincia', models.CharField(blank=True, max_length=255, verbose_name='Provincia')),
                ('id_provincia', models.CharField(blank=True, max_length=255, verbose_name='id_provincia')),
                ('pais_procedencia', models.CharField(max_length=255, verbose_name='País de Procedencia')),
                ('procedencia_entrega', models.CharField(max_length=255, verbose_name='Procedencia de la Entrega')),
                ('area_salud', models.CharField(blank=True, max_length=255, verbose_name='Área de salud')),
                ('f_inicio_sintomas', models.CharField(max_length=255, verbose_name='Síntomas iniciales')),
                ('tipo_muestra', models.CharField(max_length=255, verbose_name='Tipo de muestreo')),
                ('resultado', models.CharField(default='Pendiente', max_length=255, verbose_name='Resultado')),
                ('fecha_inicio_sintomas', models.DateField(verbose_name='Fecha inicio de síntomas')),
                ('ct', models.CharField(blank=True, max_length=255, verbose_name='CT')),
                ('fecha_salida', models.DateField(blank=True, null=True, verbose_name='Fecha del resultado')),
            ],
        ),
    ]
