# Generated by Django 2.2.16 on 2021-03-13 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataepidemiologiamodel',
            name='aislamiento',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Aislamiento'),
        ),
        migrations.AlterField(
            model_name='dataepidemiologiamodel',
            name='ci_pasaporte',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CI o Pasaporte'),
        ),
        migrations.AlterField(
            model_name='dataepidemiologiamodel',
            name='condicion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Condición'),
        ),
        migrations.AlterField(
            model_name='dataepidemiologiamodel',
            name='covid_plus',
            field=models.IntegerField(blank=True, null=True, verbose_name='Covid+'),
        ),
        migrations.AlterField(
            model_name='dataepidemiologiamodel',
            name='direccion',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='dataepidemiologiamodel',
            name='edad',
            field=models.IntegerField(blank=True, null=True, verbose_name='Edad'),
        ),
        migrations.AlterField(
            model_name='dataepidemiologiamodel',
            name='fecha_envio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de envío'),
        ),
        migrations.AlterField(
            model_name='dataepidemiologiamodel',
            name='fis',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='FIS'),
        ),
        migrations.AlterField(
            model_name='dataepidemiologiamodel',
            name='ftm',
            field=models.DateField(blank=True, null=True, verbose_name='FTM'),
        ),
        migrations.AlterField(
            model_name='dataepidemiologiamodel',
            name='muestra',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Muestra'),
        ),
        migrations.AlterField(
            model_name='dataepidemiologiamodel',
            name='municipio',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Municipio'),
        ),
        migrations.AlterField(
            model_name='dataepidemiologiamodel',
            name='no_pcr_realizado',
            field=models.IntegerField(blank=True, null=True, verbose_name='No PCR Realizado'),
        ),
        migrations.AlterField(
            model_name='dataepidemiologiamodel',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='dataepidemiologiamodel',
            name='pais',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='dataepidemiologiamodel',
            name='pcr_contactos_viajeros',
            field=models.DateField(blank=True, null=True, verbose_name='PCR de los Contactos y Viajeros'),
        ),
        migrations.AlterField(
            model_name='dataepidemiologiamodel',
            name='resultado',
            field=models.CharField(blank=True, default='Pendiente', max_length=255, null=True, verbose_name='Resultados'),
        ),
        migrations.AlterField(
            model_name='dataepidemiologiamodel',
            name='sexo',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='datahigienemodel',
            name='area_salud',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Área de salud'),
        ),
        migrations.AlterField(
            model_name='datahigienemodel',
            name='ci_pasaporte',
            field=models.CharField(blank=True, max_length=255, verbose_name='CI o Pasaporte'),
        ),
        migrations.AlterField(
            model_name='datahigienemodel',
            name='codigo',
            field=models.IntegerField(unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='datahigienemodel',
            name='condicion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Condición'),
        ),
        migrations.AlterField(
            model_name='datahigienemodel',
            name='direccion',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='datahigienemodel',
            name='edad',
            field=models.IntegerField(blank=True, verbose_name='Edad'),
        ),
        migrations.AlterField(
            model_name='datahigienemodel',
            name='f_inicio_sintomas',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Síntomas iniciales'),
        ),
        migrations.AlterField(
            model_name='datahigienemodel',
            name='fecha_inicio_sintomas',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha inicio de síntomas'),
        ),
        migrations.AlterField(
            model_name='datahigienemodel',
            name='fecha_toma_muestra',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Toma Muestra'),
        ),
        migrations.AlterField(
            model_name='datahigienemodel',
            name='id_provincia',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='id_provincia'),
        ),
        migrations.AlterField(
            model_name='datahigienemodel',
            name='municipio',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Municipio'),
        ),
        migrations.AlterField(
            model_name='datahigienemodel',
            name='pais_procedencia',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='País de Procedencia'),
        ),
        migrations.AlterField(
            model_name='datahigienemodel',
            name='procedencia_entrega',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Procedencia de la Entrega'),
        ),
        migrations.AlterField(
            model_name='datahigienemodel',
            name='provincia',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Provincia'),
        ),
        migrations.AlterField(
            model_name='datahigienemodel',
            name='resultado',
            field=models.CharField(blank=True, default='Pendiente', max_length=255, verbose_name='Resultado'),
        ),
        migrations.AlterField(
            model_name='datahigienemodel',
            name='sexo',
            field=models.CharField(blank=True, max_length=1, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='datahigienemodel',
            name='tipo_muestra',
            field=models.CharField(blank=True, max_length=255, verbose_name='Tipo de muestreo'),
        ),
    ]
