# Generated by Django 2.2.16 on 2021-03-13 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0002_auto_20210313_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='datahigienemodel',
            name='processed',
            field=models.BooleanField(default=False, verbose_name='Procesado'),
        ),
    ]
