# Generated by Django 2.2.16 on 2021-03-14 17:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0003_auto_20210314_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultmodel',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
