# Generated by Django 2.2.16 on 2021-03-14 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0003_datahigienemodel_processed'),
        ('api_rest', '0004_resultmodel_fecha'),
    ]

    operations = [
    ]
