# Generated by Django 2.2.16 on 2021-03-14 22:16

import api_rest.utils
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0004_resultmodel_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='HigieneUploadModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('archivo', models.FileField(upload_to=api_rest.utils.higiene_directory_path)),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_rest.Laboratorio')),
            ],
        ),
    ]
