# Generated by Django 2.2.16 on 2021-03-15 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0005_merge_20210314_2154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataepidemiologiamodel',
            options={'ordering': ['no_muestra'], 'verbose_name': 'Dato de Epidemiología', 'verbose_name_plural': 'Datos de Epidemiología'},
        ),
        migrations.AlterModelOptions(
            name='laboratorio',
            options={'ordering': ['nombre'], 'verbose_name': 'Laboratorio', 'verbose_name_plural': 'Laboratorios'},
        ),
        migrations.AlterModelOptions(
            name='resultmodel',
            options={'ordering': ['laboratorio', 'fecha'], 'verbose_name': 'Archivo de resultado de PCR del Laboratorio', 'verbose_name_plural': 'Archivos de resultados de PCR de los Laboratorios'},
        ),
        migrations.AlterField(
            model_name='dataepidemiologiamodel',
            name='ci_pasaporte',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Carné o Pasaporte'),
        ),
        migrations.AlterField(
            model_name='dataepidemiologiamodel',
            name='no_muestra',
            field=models.IntegerField(unique=True, verbose_name='No Muestra'),
        ),
        migrations.AlterField(
            model_name='dataepidemiologiamodel',
            name='no_pcr_realizado',
            field=models.IntegerField(blank=True, null=True, verbose_name='No PCR Realizado'),
        ),
        migrations.AlterField(
            model_name='dataepidemiologiamodel',
            name='resultado',
            field=models.CharField(blank=True, default='PENDIENTE', max_length=255, null=True, verbose_name='Resultados'),
        ),
    ]
