# Generated by Django 2.2.16 on 2021-03-15 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0006_auto_20210315_0208'),
        ('api_rest', '0005_higieneuploadmodel'),
    ]

    operations = [
    ]
