# Generated by Django 2.2.16 on 2021-03-15 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0007_merge_20210315_0234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='higieneuploadmodel',
            options={'ordering': ['laboratorio', 'fecha'], 'verbose_name': 'Archivo de muestras para detectar PCR en laboratorio', 'verbose_name_plural': 'Archivos de muestras para detectar PCR en los laboratorios'},
        ),
        migrations.AlterModelOptions(
            name='resultmodel',
            options={'ordering': ['laboratorio', 'fecha'], 'verbose_name': 'Archivo de resultado de PCR del laboratorio', 'verbose_name_plural': 'Archivos de resultados de PCR de los laboratorios'},
        ),
    ]
