# Generated by Django 2.2.16 on 2021-03-14 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0008_auto_20210315_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataepidemiologiamodel',
            name='pcr_contactos_viajeros',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='PCR de los Contactos y Viajeros'),
        ),
    ]
