# Generated by Django 2.2.16 on 2021-03-15 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0009_epidemiologiauploadmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='epidemiologiauploadmodel',
            options={'ordering': ['fecha'], 'verbose_name': 'Archivo de epidemiologia', 'verbose_name_plural': 'Archivos de epidemiologia'},
        ),
    ]
