# Generated by Django 2.2.16 on 2021-03-14 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0009_auto_20210314_1634'),
        ('api_rest', '0010_auto_20210315_0322'),
    ]

    operations = [
    ]
