# Generated by Django 2.2.16 on 2021-03-14 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0011_merge_20210314_1750'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='epidemiologiauploadmodel',
            options={'ordering': ['fecha'], 'verbose_name': 'Archivo de epidemiología', 'verbose_name_plural': 'Archivos de epidemiología'},
        ),
    ]
