# Generated by Django 2.2.16 on 2021-03-15 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0012_auto_20210314_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datahigienemodel',
            name='edad',
            field=models.IntegerField(blank=True, null=True, verbose_name='Edad'),
        ),
    ]
