# Generated by Django 2.2.16 on 2021-03-15 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0013_auto_20210315_0808'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resultmodel',
            options={'ordering': ['laboratorio', 'fecha'], 'verbose_name': 'Placa de resultado de PCR del laboratorio', 'verbose_name_plural': 'Placas de resultados de PCR de los laboratorios'},
        ),
    ]
