# Generated by Django 2.2.16 on 2021-03-17 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0015_auto_20210317_0528'),
        ('api_rest', '0015_auto_20210316_1246'),
    ]

    operations = [
    ]
