# Generated by Django 2.2.16 on 2021-03-18 00:53

import api_rest.utils
import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0016_merge_20210317_2154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataepidemiologiamodel',
            options={'ordering': ['no_muestra'], 'verbose_name': 'Resultado (Epidemiología)', 'verbose_name_plural': 'Base de datos de Resultados (Epidemiología)'},
        ),
        migrations.AlterModelOptions(
            name='datahigienemodel',
            options={'ordering': ['codigo'], 'verbose_name': 'Muestra de Laboratorio (Higiene Granma)', 'verbose_name_plural': 'Base de datos de Muestras de Laboratorio (Higiene Granma)'},
        ),
        migrations.AlterModelOptions(
            name='epidemiologiauploadmodel',
            options={'ordering': ['fecha'], 'verbose_name': 'Excel de Resultados (Epidemiología)', 'verbose_name_plural': 'Cargar Base de datos de Resultados (Epidemiología)'},
        ),
        migrations.AlterModelOptions(
            name='higieneuploadmodel',
            options={'ordering': ['laboratorio', 'fecha'], 'verbose_name': 'Excel de Muestras para PCR (Laboratorio)', 'verbose_name_plural': 'Cargar Base de datos de Muestras para PCR (Laboratorios)'},
        ),
        migrations.AlterModelOptions(
            name='laboratorio',
            options={'ordering': ['nombre'], 'verbose_name': 'Nomenclador de Laboratorio', 'verbose_name_plural': 'Nomencladores de Laboratorios'},
        ),
        migrations.AlterModelOptions(
            name='resultmodel',
            options={'ordering': ['laboratorio', 'fecha'], 'verbose_name': 'Placa de PCR (Laboratorio)', 'verbose_name_plural': 'Cargar Placas de PCR (Laboratorios)'},
        ),
        migrations.AddField(
            model_name='resultmodel',
            name='lab_procesado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='lab_procesado', to='api_rest.Laboratorio', verbose_name='Laboratorio (procesado)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='epidemiologiauploadmodel',
            name='archivo',
            field=models.FileField(upload_to=api_rest.utils.epidemiologia_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xls', 'xlsx'])]),
        ),
        migrations.AlterField(
            model_name='higieneuploadmodel',
            name='archivo',
            field=models.FileField(upload_to=api_rest.utils.higiene_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xls', 'xlsx'])]),
        ),
        migrations.AlterField(
            model_name='resultmodel',
            name='archivo',
            field=models.FileField(upload_to=api_rest.utils.lab_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xls', 'xlsx'])]),
        ),
        migrations.AlterField(
            model_name='resultmodel',
            name='fecha',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha del resultado'),
        ),
        migrations.AlterField(
            model_name='resultmodel',
            name='laboratorio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_rest.Laboratorio', verbose_name='Laboratorio (enviado)'),
        ),
    ]
