# Generated by Django 2.2.16 on 2021-03-18 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0017_auto_20210317_1307'),
        ('api_rest', '0016_merge_20210317_2154'),
    ]

    operations = [
    ]
