# Generated by Django 2.2.16 on 2021-03-18 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0018_merge_20210318_1122'),
        ('api_rest', '0018_merge_20210318_0315'),
    ]

    operations = [
    ]
