# Generated by Django 2.2.16 on 2021-03-19 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0019_merge_20210318_1218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testresult',
            options={'verbose_name': 'Nomenclador de resultado de PCR', 'verbose_name_plural': 'Nomenclador de resultado de PCR'},
        ),
    ]
