# Generated by Django 2.2.16 on 2021-03-19 04:12

import api_rest.utils
import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0019_merge_20210318_1218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testresult',
            options={'verbose_name': 'Nomenclador de resultado de PCR', 'verbose_name_plural': 'Nomenclador de resultado de PCR'},
        ),
        migrations.AddField(
            model_name='datahigienemodel',
            name='fecha_envio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha del envío'),
        ),
        migrations.AlterField(
            model_name='higieneuploadmodel',
            name='fecha',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha de envío'),
        ),
        migrations.AlterField(
            model_name='resultmodel',
            name='archivo',
            field=models.FileField(upload_to=api_rest.utils.lab_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xls', 'xlsx'])], verbose_name='Archivo Excel'),
        ),
        migrations.AlterField(
            model_name='resultmodel',
            name='lab_procesado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_procesado', to='api_rest.Laboratorio', verbose_name='Laboratorio (Procesado)'),
        ),
        migrations.AlterField(
            model_name='resultmodel',
            name='laboratorio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_rest.Laboratorio', verbose_name='Laboratorio (Enviado)'),
        ),
    ]
