# Generated by Django 2.2.16 on 2021-03-19 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0022_auto_20210319_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datahigienemodel',
            name='processed',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Procesado'),
        ),
    ]
