# Generated by Django 2.2.16 on 2021-03-19 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0020_auto_20210319_0055'),
        ('api_rest', '0023_auto_20210319_0549'),
    ]

    operations = [
    ]
