# Generated by Django 2.2.16 on 2021-03-23 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0024_merge_20210319_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datahigienemodel',
            name='id_provincia',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Id Provincia'),
        ),
        migrations.AlterField(
            model_name='datahigienemodel',
            name='laboratorio',
            field=models.CharField(max_length=255, verbose_name='Laboratorio Enviada'),
        ),
        migrations.AlterField(
            model_name='datahigienemodel',
            name='resultado',
            field=models.CharField(blank=True, default='PENDIENTE', max_length=255, null=True, verbose_name='Resultado'),
        ),
    ]
