# Generated by Django 2.2.16 on 2021-03-23 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0025_auto_20210322_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datahigienemodel',
            name='fecha_salida',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Salida'),
        ),
    ]
