# Generated by Django 2.2.16 on 2021-03-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0026_auto_20210322_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datahigienemodel',
            name='area_salud',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Área de Salud'),
        ),
        migrations.AlterField(
            model_name='datahigienemodel',
            name='ci_pasaporte',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='C Identidad/ Pasaporte'),
        ),
        migrations.AlterField(
            model_name='datahigienemodel',
            name='ct',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ct'),
        ),
        migrations.AlterField(
            model_name='datahigienemodel',
            name='f_inicio_sintomas',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Síntomas Iniciales'),
        ),
        migrations.AlterField(
            model_name='datahigienemodel',
            name='fecha_envio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha del Envío'),
        ),
        migrations.AlterField(
            model_name='datahigienemodel',
            name='fecha_inicio_sintomas',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha/ Inicio de Síntomas'),
        ),
        migrations.AlterField(
            model_name='datahigienemodel',
            name='nombre_apellidos',
            field=models.CharField(max_length=255, verbose_name='Nombre y Apellidos'),
        ),
        migrations.AlterField(
            model_name='datahigienemodel',
            name='tipo_muestra',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tipo de Muestreo'),
        ),
    ]
