# Generated by Django 2.2.16 on 2021-03-24 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0027_auto_20210323_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataepidemiologiamodel',
            name='laboratorio',
            field=models.CharField(choices=[('HABANA', 'La Habana'), ('SANTIAGO', 'Santiago de Cuba'), ('ARTEMISA', 'Artemisa'), ('CAMAGUEY', 'Camagüey'), ('CIEGODEAVILA', 'Ciego de Ávila'), ('CIENFUEGOS', 'Cienfuegos'), ('GRANMA', 'Granma'), ('GUANTANAMO', 'Guantánamo'), ('HOLGUIN', 'Hoguín'), ('IPK', 'IPK'), ('MATANZAS', 'Matanzas'), ('PINARDELRIO', 'Pinar del Río'), ('TUNAS', 'Las Tunas'), ('VILLACLARA', 'Villa Clara')], max_length=255, verbose_name='Laboratorio'),
        ),
        migrations.AlterField(
            model_name='datahigienemodel',
            name='laboratorio',
            field=models.CharField(choices=[('HABANA', 'La Habana'), ('SANTIAGO', 'Santiago de Cuba'), ('ARTEMISA', 'Artemisa'), ('CAMAGUEY', 'Camagüey'), ('CIEGODEAVILA', 'Ciego de Ávila'), ('CIENFUEGOS', 'Cienfuegos'), ('GRANMA', 'Granma'), ('GUANTANAMO', 'Guantánamo'), ('HOLGUIN', 'Hoguín'), ('IPK', 'IPK'), ('MATANZAS', 'Matanzas'), ('PINARDELRIO', 'Pinar del Río'), ('TUNAS', 'Las Tunas'), ('VILLACLARA', 'Villa Clara')], max_length=255, verbose_name='Laboratorio enviada'),
        ),
    ]
