# Generated by Django 2.2.16 on 2021-03-27 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0030_resultregister'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultregister',
            name='result_date',
            field=models.DateField(),
        ),
    ]
