# Generated by Django 2.2.16 on 2021-03-29 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0031_auto_20210327_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultregister',
            name='result',
            field=models.CharField(max_length=255, verbose_name='Resultado'),
        ),
        migrations.AlterField(
            model_name='resultregister',
            name='result_date',
            field=models.DateField(verbose_name='Fecha de resultado'),
        ),
        migrations.AlterField(
            model_name='resultregister',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_rest.DataEpidemiologiaModel', verbose_name='Muestra'),
        ),
    ]
