# Generated by Django 2.2.16 on 2021-03-29 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0032_auto_20210329_1509'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataepidemiologiamodel',
            options={'ordering': ['no_muestra'], 'verbose_name': 'Base de datos de resultado', 'verbose_name_plural': 'Base de datos de resultados'},
        ),
        migrations.AlterModelOptions(
            name='datahigienemodel',
            options={'ordering': ['codigo'], 'verbose_name': 'Base de datos de muestras', 'verbose_name_plural': 'Bases de datos de muestras'},
        ),
        migrations.AlterModelOptions(
            name='epidemiologiauploadmodel',
            options={'ordering': ['fecha'], 'verbose_name': 'Restaurar resultado', 'verbose_name_plural': 'Restaurar resultados'},
        ),
        migrations.AlterModelOptions(
            name='higieneuploadmodel',
            options={'ordering': ['laboratorio', 'fecha'], 'verbose_name': 'Cargar muestra', 'verbose_name_plural': 'Cargar muestras'},
        ),
        migrations.AlterModelOptions(
            name='resultmodel',
            options={'ordering': ['laboratorio', 'fecha'], 'verbose_name': 'Cargar resultado', 'verbose_name_plural': 'Cargar resultados'},
        ),
    ]
