# Generated by Django 2.2.16 on 2021-03-31 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0034_auto_20210330_2249'),
        ('api_rest', '0035_auto_20210331_1002'),
    ]

    operations = [
    ]
