# Generated by Django 2.2.16 on 2021-03-31 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0036_merge_20210331_1118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataepidemiologiamodel',
            options={'ordering': ['no_muestra'], 'verbose_name': 'Base de datos de resultado', 'verbose_name_plural': 'Base de datos de resultados'},
        ),
    ]
