# Generated by Django 2.2.16 on 2021-04-02 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0037_auto_20210331_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroAislamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Centro de Aislamiento',
                'verbose_name_plural': 'Centros de Aislamiento',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
            },
        ),
    ]
