# Generated by Django 2.2.16 on 2021-04-02 20:47

import api_rest.utils
import api_rest.validators
import django.core.validators
from django.db import migrations
import protected_media.models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0038_centroaislamiento_municipio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='higieneuploadmodel',
            name='archivo',
            field=protected_media.models.ProtectedFileField(storage=protected_media.models.ProtectedFileSystemStorage(), upload_to=api_rest.utils.higiene_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx']), api_rest.validators.validate_file_size]),
        ),
    ]
