# Generated by Django 2.2.16 on 2021-04-06 01:02

import api_rest.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0039_auto_20210405_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epidemiologiauploadmodel',
            name='archivo',
            field=models.FileField(upload_to=api_rest.utils.epidemiologia_directory_path),
        ),
        migrations.AlterField(
            model_name='higieneuploadmodel',
            name='archivo',
            field=models.FileField(upload_to=api_rest.utils.higiene_directory_path),
        ),
    ]
