# Generated by Django 2.2.16 on 2021-04-02 23:49

import api_rest.utils
import api_rest.validators
import django.core.validators
from django.db import migrations
import protected_media.models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0039_auto_20210402_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epidemiologiauploadmodel',
            name='archivo',
            field=protected_media.models.ProtectedFileField(storage=protected_media.models.ProtectedFileSystemStorage(), upload_to=api_rest.utils.epidemiologia_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx'])]),
        ),
        migrations.AlterField(
            model_name='resultmodel',
            name='archivo',
            field=protected_media.models.ProtectedFileField(storage=protected_media.models.ProtectedFileSystemStorage(), upload_to=api_rest.utils.lab_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx']), api_rest.validators.validate_file_size], verbose_name='Archivo Excel'),
        ),
    ]
