# Generated by Django 2.2.16 on 2021-04-07 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0040_auto_20210405_2102'),
        ('api_rest', '0040_auto_20210402_1949'),
    ]

    operations = [
    ]
