# Generated by Django 2.2.16 on 2021-04-07 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_rest', '0040_auto_20210405_2102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='municipio',
            old_name='nombre',
            new_name='city',
        ),
        migrations.AddField(
            model_name='centroaislamiento',
            name='municipio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api_rest.Municipio'),
        ),
        migrations.AddField(
            model_name='centroaislamiento',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='centro', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='municipio',
            name='country',
            field=models.CharField(blank=True, default='Cuba', max_length=255, verbose_name='Pais'),
        ),
        migrations.AddField(
            model_name='municipio',
            name='lat',
            field=models.DecimalField(decimal_places=5, max_digits=8, null=True, verbose_name='Latitud'),
        ),
        migrations.AddField(
            model_name='municipio',
            name='lng',
            field=models.DecimalField(decimal_places=5, max_digits=8, null=True, verbose_name='Longitud'),
        ),
        migrations.AddField(
            model_name='municipio',
            name='population',
            field=models.PositiveIntegerField(null=True, verbose_name='Habitantes'),
        ),
        migrations.AddField(
            model_name='municipio',
            name='province',
            field=models.CharField(blank=True, max_length=255, verbose_name='Provincia'),
        ),
        migrations.AddField(
            model_name='resultregister',
            name='new_result',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nuevo Resultado'),
        ),
        migrations.AddField(
            model_name='resultregister',
            name='new_result_date',
            field=models.DateField(null=True, verbose_name='Nueva fecha de resultado'),
        ),
        migrations.AlterField(
            model_name='centroaislamiento',
            name='nombre',
            field=models.CharField(max_length=255, verbose_name='Nombre del Centro'),
        ),
        migrations.AlterField(
            model_name='dataepidemiologiamodel',
            name='laboratorio',
            field=models.CharField(choices=[('HABANA', 'La Habana'), ('SANTIAGO', 'Santiago de Cuba'), ('ARTEMISA', 'Artemisa'), ('CAMAGUEY', 'Camagüey'), ('CIEGODEAVILA', 'Ciego de Ávila'), ('CIENFUEGOS', 'Cienfuegos'), ('GRANMA', 'Granma'), ('GUANTANAMO', 'Guantánamo'), ('HOLGUIN', 'Holguín'), ('IPK', 'IPK'), ('MATANZAS', 'Matanzas'), ('PINARDELRIO', 'Pinar del Río'), ('TUNAS', 'Las Tunas'), ('VILLACLARA', 'Villa Clara')], max_length=255, verbose_name='Laboratorio'),
        ),
        migrations.AlterField(
            model_name='datahigienemodel',
            name='laboratorio',
            field=models.CharField(choices=[('HABANA', 'La Habana'), ('SANTIAGO', 'Santiago de Cuba'), ('ARTEMISA', 'Artemisa'), ('CAMAGUEY', 'Camagüey'), ('CIEGODEAVILA', 'Ciego de Ávila'), ('CIENFUEGOS', 'Cienfuegos'), ('GRANMA', 'Granma'), ('GUANTANAMO', 'Guantánamo'), ('HOLGUIN', 'Holguín'), ('IPK', 'IPK'), ('MATANZAS', 'Matanzas'), ('PINARDELRIO', 'Pinar del Río'), ('TUNAS', 'Las Tunas'), ('VILLACLARA', 'Villa Clara')], max_length=255, verbose_name='Laboratorio enviada'),
        ),
    ]
