# Generated by Django 2.2.16 on 2021-04-08 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0041_auto_20210407_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataepidemiologiamodel',
            name='hora',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora del resultado'),
        ),
    ]
