# Generated by Django 2.2.16 on 2021-04-08 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0041_merge_20210407_1629'),
        ('api_rest', '0042_dataepidemiologiamodel_hora'),
    ]

    operations = [
    ]
