# Generated by Django 2.2.16 on 2021-04-09 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0044_auto_20210408_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultregister',
            name='new_result',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nuevo resultado'),
        ),
    ]
