# Generated by Django 2.2.16 on 2021-04-14 15:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0046_auto_20210414_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultmodel',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 14, 11, 25, 46, 459409), verbose_name='Fecha del resultado'),
        ),
    ]
