# Generated by Django 2.2.16 on 2021-04-18 22:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0048_auto_20210417_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultmodel',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 18, 18, 42, 45, 580743), verbose_name='Fecha del resultado'),
        ),
    ]
