# Generated by Django 2.2.16 on 2021-04-18 15:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0048_auto_20210418_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultmodel',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 18, 11, 46, 44, 375708), verbose_name='Fecha del resultado'),
        ),
    ]
