# Generated by Django 2.2.16 on 2021-04-18 18:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0048_auto_20210418_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultmodel',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 18, 14, 34, 9, 690668), verbose_name='Fecha del resultado'),
        ),
    ]
