# Generated by Django 2.2.16 on 2021-04-19 03:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0050_auto_20210418_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultmodel',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 18, 23, 21, 26, 358366), verbose_name='Fecha del resultado'),
        ),
    ]
