# Generated by Django 2.2.16 on 2021-04-19 18:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0051_auto_20210418_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultmodel',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 19, 14, 41, 53, 728414), verbose_name='Fecha del resultado'),
        ),
    ]
