# Generated by Django 2.2.16 on 2021-04-18 18:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0052_auto_20210418_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultmodel',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 18, 14, 44, 59, 407552), verbose_name='Fecha del resultado'),
        ),
    ]
