# Generated by Django 2.2.16 on 2021-04-21 20:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0053_auto_20210420_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultmodel',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 21, 16, 22, 27, 515717), verbose_name='Fecha del resultado'),
        ),
    ]
