# Generated by Django 2.2.16 on 2021-04-18 18:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0053_auto_20210418_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultmodel',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 18, 14, 48, 34, 773208), verbose_name='Fecha del resultado'),
        ),
    ]
