# Generated by Django 2.2.16 on 2021-04-18 18:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0055_auto_20210418_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultmodel',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 18, 14, 59, 5, 506140), verbose_name='Fecha del resultado'),
        ),
    ]
