# Generated by Django 2.2.16 on 2021-04-23 15:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0055_auto_20210421_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultmodel',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 23, 11, 36, 36, 639843), verbose_name='Fecha del resultado'),
        ),
    ]
