# Generated by Django 2.2.16 on 2021-04-18 19:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0056_auto_20210418_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultmodel',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 18, 15, 1, 45, 573394), verbose_name='Fecha del resultado'),
        ),
    ]
