# Generated by Django 2.2.16 on 2021-04-18 19:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0057_auto_20210418_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultmodel',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 18, 15, 4, 39, 61746), verbose_name='Fecha del resultado'),
        ),
    ]
