# Generated by Django 2.2.16 on 2021-04-18 19:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0058_auto_20210418_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultmodel',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 18, 15, 34, 25, 136329), verbose_name='Fecha del resultado'),
        ),
    ]
