# Generated by Django 2.2.16 on 2021-04-18 19:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0059_auto_20210418_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultmodel',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 18, 15, 39, 48, 970341), verbose_name='Fecha del resultado'),
        ),
    ]
