# Generated by Django 2.2.16 on 2021-04-19 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0048_auto_20210418_1722'),
        ('api_rest', '0060_auto_20210418_1539'),
    ]

    operations = [
    ]
