# Generated by Django 2.2.16 on 2021-04-19 01:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0062_auto_20210418_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultmodel',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 18, 21, 42, 9, 635284), verbose_name='Fecha del resultado'),
        ),
    ]
