# Generated by Django 2.2.16 on 2021-04-18 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0049_auto_20210418_1146'),
        ('api_rest', '0063_auto_20210418_2142'),
    ]

    operations = [
    ]
