# Generated by Django 2.2.16 on 2021-04-18 16:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0067_auto_20210418_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultmodel',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 18, 12, 42, 18, 764329), verbose_name='Fecha del resultado'),
        ),
    ]
