# Generated by Django 2.2.16 on 2021-04-21 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0069_trigger_after_delete_muestra_20210419_1306'),
        ('api_rest', '0068_auto_20210418_1242'),
    ]

    operations = [
    ]
