# Generated by Django 2.2.16 on 2021-04-23 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0070_merge_20210421_1901'),
        ('api_rest', '0070_merge_20210420_1134'),
    ]

    operations = [
    ]
