# Generated by Django 2.2.16 on 2021-04-23 04:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0071_merge_20210423_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultmodel',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha del resultado'),
        ),
    ]
