# Generated by Django 2.2.16 on 2021-04-27 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0072_auto_20210423_0017'),
        ('api_rest', '0056_auto_20210423_1136'),
    ]

    operations = [
    ]
