# Generated by Django 2.2.16 on 2021-04-27 20:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0073_merge_20210427_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultmodel',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha del resultado'),
        ),
    ]
