# Generated by Django 2.2.16 on 2021-03-19 01:14

import django.contrib.postgres.fields.hstore
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('error', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataHigieneError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.CharField(max_length=255, verbose_name='Error')),
                ('archivo', models.CharField(max_length=255, verbose_name='Archivo')),
                ('data', django.contrib.postgres.fields.hstore.HStoreField()),
            ],
        ),
    ]
