# Generated by Django 2.2.16 on 2021-03-19 02:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('error', '0002_datahigieneerror'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datahigieneerror',
            options={'ordering': ['codigo'], 'verbose_name': 'Error de muestra de Laboratorio (Higiene Granma)', 'verbose_name_plural': 'Errores de muestra datos de Muestras de             Laboratorio (Higiene Granma)'},
        ),
        migrations.RemoveField(
            model_name='datahigieneerror',
            name='data',
        ),
        migrations.AddField(
            model_name='datahigieneerror',
            name='area_salud',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Área de salud'),
        ),
        migrations.AddField(
            model_name='datahigieneerror',
            name='ci_pasaporte',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='CI o Pasaporte'),
        ),
        migrations.AddField(
            model_name='datahigieneerror',
            name='codigo',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='datahigieneerror',
            name='condicion',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Condición'),
        ),
        migrations.AddField(
            model_name='datahigieneerror',
            name='ct',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='CT'),
        ),
        migrations.AddField(
            model_name='datahigieneerror',
            name='direccion',
            field=models.TextField(blank=True, default='', verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='datahigieneerror',
            name='edad',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Edad'),
        ),
        migrations.AddField(
            model_name='datahigieneerror',
            name='f_inicio_sintomas',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Síntomas iniciales'),
        ),
        migrations.AddField(
            model_name='datahigieneerror',
            name='fecha',
            field=models.DateField(auto_now_add=True, default=datetime.date(2021, 3, 19)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datahigieneerror',
            name='fecha_inicio_sintomas',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Fecha inicio de síntomas'),
        ),
        migrations.AddField(
            model_name='datahigieneerror',
            name='fecha_salida',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Fecha del resultado'),
        ),
        migrations.AddField(
            model_name='datahigieneerror',
            name='fecha_toma_muestra',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Fecha de Toma Muestra'),
        ),
        migrations.AddField(
            model_name='datahigieneerror',
            name='id_provincia',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='id_provincia'),
        ),
        migrations.AddField(
            model_name='datahigieneerror',
            name='laboratorio',
            field=models.CharField(blank=True, max_length=255, verbose_name='Laboratorio'),
        ),
        migrations.AddField(
            model_name='datahigieneerror',
            name='municipio',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Municipio'),
        ),
        migrations.AddField(
            model_name='datahigieneerror',
            name='nombre_apellidos',
            field=models.CharField(default='', max_length=255, verbose_name='Nombres y Apellidos'),
        ),
        migrations.AddField(
            model_name='datahigieneerror',
            name='pais_procedencia',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='País de Procedencia'),
        ),
        migrations.AddField(
            model_name='datahigieneerror',
            name='procedencia_entrega',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Procedencia de la Entrega'),
        ),
        migrations.AddField(
            model_name='datahigieneerror',
            name='provincia',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Provincia'),
        ),
        migrations.AddField(
            model_name='datahigieneerror',
            name='sexo',
            field=models.CharField(blank=True, default='', max_length=1, verbose_name='Sexo'),
        ),
        migrations.AddField(
            model_name='datahigieneerror',
            name='tipo_muestra',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Tipo de muestreo'),
        ),
    ]
