# Generated by Django 2.2.16 on 2021-03-19 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('error', '0003_auto_20210319_0250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datahigieneerror',
            old_name='archivo',
            new_name='nombre_archivo',
        ),
    ]
