# Generated by Django 2.2.16 on 2021-03-19 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('error', '0005_auto_20210319_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataEpidemiologiaError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.CharField(max_length=255, verbose_name='Causa')),
                ('nombre_archivo', models.CharField(max_length=255, verbose_name='Archivo')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha en que se procesó el archivo')),
                ('covid_plus', models.CharField(blank=True, max_length=255, verbose_name='Covid+')),
                ('no_pcr_realizado', models.CharField(blank=True, max_length=255, verbose_name='No PCR Realizado')),
                ('no_muestra', models.CharField(blank=True, max_length=255, verbose_name='No Muestra')),
                ('laboratorio', models.CharField(max_length=255, verbose_name='Laboratorio')),
                ('nombre_apellido', models.CharField(max_length=255, verbose_name='Nombres y Apellidos')),
                ('ci_pasaporte', models.CharField(blank=True, max_length=255, null=True, verbose_name='Carné o Pasaporte')),
                ('edad', models.CharField(blank=True, max_length=255, verbose_name='Edad')),
                ('sexo', models.CharField(blank=True, max_length=1, null=True, verbose_name='Sexo')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('municipio', models.CharField(blank=True, max_length=255, null=True, verbose_name='Municipio')),
                ('aislamiento', models.CharField(blank=True, max_length=255, null=True, verbose_name='Aislamiento')),
                ('fis', models.CharField(blank=True, max_length=255, null=True, verbose_name='FIS')),
                ('muestra', models.CharField(blank=True, max_length=255, null=True, verbose_name='Muestra')),
                ('ftm', models.CharField(blank=True, max_length=255, verbose_name='FTM')),
                ('fecha_envio', models.CharField(blank=True, max_length=255, verbose_name='Fecha de envío')),
                ('resultado', models.CharField(blank=True, default='PENDIENTE', max_length=255, verbose_name='Resultados')),
                ('fecha_resultado', models.CharField(blank=True, max_length=255, verbose_name='Fecha del resultado')),
                ('pcr_contactos_viajeros', models.CharField(blank=True, max_length=255, null=True, verbose_name='PCR de los Contactos y Viajeros')),
                ('condicion', models.CharField(blank=True, max_length=255, verbose_name='Condición')),
                ('pais', models.CharField(blank=True, max_length=255, verbose_name='País')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Error en base de datos resultado (Epidemiología)',
                'verbose_name_plural': 'Errores en base de datos             de Resultados (Epidemiología)',
            },
        ),
        migrations.AlterModelOptions(
            name='datahigieneerror',
            options={'verbose_name': 'Error de muestra de Laboratorio (Higiene Granma)', 'verbose_name_plural': 'Errores de muestra datos de Muestras de             Laboratorio (Higiene Granma)'},
        ),
    ]
