# Generated by Django 2.2.16 on 2021-03-19 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('error', '0006_auto_20210319_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacaErrorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.CharField(max_length=255, verbose_name='Causa')),
                ('nombre_archivo', models.CharField(max_length=255, verbose_name='Archivo')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha en que se procesó el archivo')),
                ('laboratorio', models.CharField(blank=True, max_length=255, verbose_name='Laboratorio')),
                ('no_muestra', models.CharField(blank=True, default='', max_length=255, verbose_name='Código')),
                ('ci', models.CharField(blank=True, default='', max_length=255, verbose_name='CI o Pasaporte')),
                ('edad', models.CharField(blank=True, default='', max_length=255, verbose_name='Edad')),
                ('sexo', models.CharField(blank=True, default='', max_length=255, verbose_name='Sexo')),
                ('nombre_apellidos', models.CharField(default='', max_length=255, verbose_name='Nombres y Apellidos')),
                ('municipio', models.CharField(blank=True, default='', max_length=255, verbose_name='Municipio')),
                ('provincia', models.CharField(blank=True, default='', max_length=255, verbose_name='Provincia')),
                ('resultado', models.CharField(blank=True, default='', max_length=255, verbose_name='Resultado')),
                ('fecha_resultado', models.CharField(blank=True, default='', max_length=255, verbose_name='Fecha del resultado')),
            ],
            options={
                'verbose_name': 'Error de muestra de Laboratorio (Higiene Granma)',
                'verbose_name_plural': 'Errores de muestra datos de Muestras de             Laboratorio (Higiene Granma)',
            },
        ),
        migrations.AlterField(
            model_name='dataepidemiologiaerror',
            name='laboratorio',
            field=models.CharField(blank=True, max_length=255, verbose_name='Laboratorio'),
        ),
        migrations.AlterField(
            model_name='dataepidemiologiaerror',
            name='nombre_apellido',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nombres y Apellidos'),
        ),
    ]
