# Generated by Django 2.2.16 on 2021-03-19 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('error', '0009_auto_20210319_1701'),
        ('error', '0009_auto_20210319_1707'),
    ]

    operations = [
    ]
