# Generated by Django 2.2.16 on 2021-03-19 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('error', '0009_auto_20210319_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataepidemiologiaerror',
            name='condicion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Condición'),
        ),
        migrations.AlterField(
            model_name='dataepidemiologiaerror',
            name='covid_plus',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Covid+'),
        ),
        migrations.AlterField(
            model_name='dataepidemiologiaerror',
            name='edad',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Edad'),
        ),
        migrations.AlterField(
            model_name='dataepidemiologiaerror',
            name='fecha_envio',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Fecha de envío'),
        ),
        migrations.AlterField(
            model_name='dataepidemiologiaerror',
            name='fecha_resultado',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Fecha del resultado'),
        ),
        migrations.AlterField(
            model_name='dataepidemiologiaerror',
            name='ftm',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='FTM'),
        ),
        migrations.AlterField(
            model_name='dataepidemiologiaerror',
            name='laboratorio',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Laboratorio'),
        ),
        migrations.AlterField(
            model_name='dataepidemiologiaerror',
            name='no_muestra',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='No Muestra'),
        ),
        migrations.AlterField(
            model_name='dataepidemiologiaerror',
            name='no_pcr_realizado',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='No PCR Realizado'),
        ),
        migrations.AlterField(
            model_name='dataepidemiologiaerror',
            name='nombre_apellido',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombres y Apellidos'),
        ),
        migrations.AlterField(
            model_name='dataepidemiologiaerror',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='dataepidemiologiaerror',
            name='pais',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='dataepidemiologiaerror',
            name='resultado',
            field=models.CharField(blank=True, default='PENDIENTE', max_length=255, null=True, verbose_name='Resultados'),
        ),
        migrations.AlterField(
            model_name='datahigieneerror',
            name='area_salud',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Área de salud'),
        ),
        migrations.AlterField(
            model_name='datahigieneerror',
            name='ci_pasaporte',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CI o Pasaporte'),
        ),
        migrations.AlterField(
            model_name='datahigieneerror',
            name='codigo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='datahigieneerror',
            name='condicion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Condición'),
        ),
        migrations.AlterField(
            model_name='datahigieneerror',
            name='ct',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CT'),
        ),
        migrations.AlterField(
            model_name='datahigieneerror',
            name='direccion',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='datahigieneerror',
            name='edad',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Edad'),
        ),
        migrations.AlterField(
            model_name='datahigieneerror',
            name='f_inicio_sintomas',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Síntomas iniciales'),
        ),
        migrations.AlterField(
            model_name='datahigieneerror',
            name='fecha_inicio_sintomas',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Fecha inicio de síntomas'),
        ),
        migrations.AlterField(
            model_name='datahigieneerror',
            name='fecha_salida',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Fecha del resultado'),
        ),
        migrations.AlterField(
            model_name='datahigieneerror',
            name='fecha_toma_muestra',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Fecha de Toma Muestra'),
        ),
        migrations.AlterField(
            model_name='datahigieneerror',
            name='id_provincia',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='id_provincia'),
        ),
        migrations.AlterField(
            model_name='datahigieneerror',
            name='laboratorio',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Laboratorio'),
        ),
        migrations.AlterField(
            model_name='datahigieneerror',
            name='municipio',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Municipio'),
        ),
        migrations.AlterField(
            model_name='datahigieneerror',
            name='nombre_apellidos',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombres y Apellidos'),
        ),
        migrations.AlterField(
            model_name='datahigieneerror',
            name='pais_procedencia',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='País de Procedencia'),
        ),
        migrations.AlterField(
            model_name='datahigieneerror',
            name='procedencia_entrega',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Procedencia de la Entrega'),
        ),
        migrations.AlterField(
            model_name='datahigieneerror',
            name='provincia',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Provincia'),
        ),
        migrations.AlterField(
            model_name='datahigieneerror',
            name='sexo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='datahigieneerror',
            name='tipo_muestra',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tipo de muestreo'),
        ),
        migrations.AlterField(
            model_name='placaerrormodel',
            name='ci',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CI o Pasaporte'),
        ),
        migrations.AlterField(
            model_name='placaerrormodel',
            name='edad',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Edad'),
        ),
        migrations.AlterField(
            model_name='placaerrormodel',
            name='fecha_resultado',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Fecha del resultado'),
        ),
        migrations.AlterField(
            model_name='placaerrormodel',
            name='laboratorio',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Laboratorio'),
        ),
        migrations.AlterField(
            model_name='placaerrormodel',
            name='municipio',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Municipio'),
        ),
        migrations.AlterField(
            model_name='placaerrormodel',
            name='no_muestra',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='placaerrormodel',
            name='nombre_apellidos',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombres y Apellidos'),
        ),
        migrations.AlterField(
            model_name='placaerrormodel',
            name='provincia',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Provincia'),
        ),
        migrations.AlterField(
            model_name='placaerrormodel',
            name='resultado',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Resultado'),
        ),
        migrations.AlterField(
            model_name='placaerrormodel',
            name='sexo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sexo'),
        ),
    ]
