# Generated by Django 2.2.16 on 2021-03-20 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('error', '0010_merge_20210319_1848'),
        ('error', '0010_auto_20210319_2111'),
    ]

    operations = [
    ]
