# Generated by Django 2.2.16 on 2021-03-24 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('error', '0011_merge_20210320_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='datahigieneerror',
            name='fecha_envio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha del Envío'),
        ),
        migrations.AddField(
            model_name='placaerrormodel',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
    ]
