# Generated by Django 2.2.16 on 2021-03-31 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('error', '0013_auto_20210329_1845'),
        ('error', '0013_auto_20210330_1912'),
    ]

    operations = [
    ]
