# Generated by Django 2.2.16 on 2021-04-07 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('error', '0014_merge_20210331_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataepidemiologiaerror',
            name='hora',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Hora del resultado'),
        ),
        migrations.AddField(
            model_name='placaerrormodel',
            name='hora',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Hora del resultado'),
        ),
    ]
