# Generated by Django 2.2.16 on 2021-04-18 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_server_access_logs', '0002_auto_20210418_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslogsmodel',
            name='username',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre de Usuario'),
        ),
    ]
